// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skillworks.Core.TranscriptStore;

#nullable disable

namespace Skillworks.Core.TranscriptStore.Migrations
{
    [DbContext(typeof(TranscriptStoreDbContext))]
    [Migration("20260913201745_FilterableInstants")]
    partial class FilterableInstants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Skillworks.Core.Telemetry.Activation", b =>
                {
                    b.Property<string>("ToolUseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ToolUseId");

                    b.HasIndex("Repository");

                    b.HasIndex("SkillName");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Activations");
                });

            modelBuilder.Entity("Skillworks.Core.Telemetry.IngestedTranscript", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("Lines")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Path");

                    b.ToTable("IngestedTranscripts");
                });

            modelBuilder.Entity("Skillworks.Core.Telemetry.ModelPrice", b =>
                {
                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheReadPerMillion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheWrite1hPerMillion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CacheWrite5mPerMillion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InputPerMillion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutputPerMillion")
                        .HasColumnType("TEXT");

                    b.HasKey("Model");

                    b.ToTable("ModelPrices");

                    b.HasData(
                        new
                        {
                            Model = "claude-opus-5",
                            CacheReadPerMillion = 1.50m,
                            CacheWrite1hPerMillion = 30m,
                            CacheWrite5mPerMillion = 18.75m,
                            InputPerMillion = 15m,
                            OutputPerMillion = 75m
                        },
                        new
                        {
                            Model = "claude-sonnet-5",
                            CacheReadPerMillion = 0.30m,
                            CacheWrite1hPerMillion = 6m,
                            CacheWrite5mPerMillion = 3.75m,
                            InputPerMillion = 3m,
                            OutputPerMillion = 15m
                        },
                        new
                        {
                            Model = "claude-haiku-4-5",
                            CacheReadPerMillion = 0.10m,
                            CacheWrite1hPerMillion = 2m,
                            CacheWrite5mPerMillion = 1.25m,
                            InputPerMillion = 1m,
                            OutputPerMillion = 5m
                        });
                });

            modelBuilder.Entity("Skillworks.Core.Telemetry.TranscriptFault", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NoticedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Path", "Line");

                    b.ToTable("TranscriptFaults");
                });

            modelBuilder.Entity("Skillworks.Core.Telemetry.Turn", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWrite1hTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CacheWrite5mTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Effort")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Repository")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .HasColumnType("TEXT");

                    b.Property<long>("ThinkingTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("RequestId");

                    b.HasIndex("Repository");

                    b.HasIndex("SkillName");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
