// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skillworks.Core.TelemetryStore;

#nullable disable

namespace Skillworks.Core.TelemetryStore.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260913174411_Telemetry")]
    partial class Telemetry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Skillworks.Core.Telemetry.Activation", b =>
                {
                    b.Property<string>("ToolUseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitBranch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ToolUseId");

                    b.HasIndex("SkillName");

                    b.ToTable("Activations");
                });

            modelBuilder.Entity("Skillworks.Core.Telemetry.IngestedTranscript", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.Property<long>("Offset")
                        .HasColumnType("INTEGER");

                    b.HasKey("Path");

                    b.ToTable("IngestedTranscripts");
                });
#pragma warning restore 612, 618
        }
    }
}
